### ISSUE TITLE
Anachronism Warning

### ISSUE THREAD

**Issue by AlexWyrmin** [Leviathonlx/MoreBookmarks-Plus#111]
By the time of Charlemagne, the Jutes had already vanished from the ethnographic map of Europe and their former homeland, the Jutland peninsula, had become culturally Dane one or two centuries prior.

**Comment by Leviathonlx** [comment]
All the cultures I added were finishing the integration of CE. Overall they did a lot of research for what they added but even if something was slightly off I'm fine since in the end I'd rather a more interesting map setup or gameplay reasons.

**Comment by AlexWyrmin** [comment]
If that's the case, no problem. I just pointed this anachronism out in the eventuality it had flown under the radar for some reason.

**Comment by Leviathonlx** [comment]
Yea I asked the CE team about it anyway and it seems it's mostly a 'there's barely any sources for that region anyway'
