### ISSUE TITLE
Game Still Crashing

### ISSUE THREAD

**Issue by AlexWyrmin** [Leviathonlx/MoreBookmarks-Plus#135]
I tried to launch the game with only MB enabled, after downloading the latest patch you made to it, but it crashed anyway. Attached below is the error.log the crash generated.
[error.log](https://github.com/Leviathonlx/MoreBookmarks-Plus/files/9539931/error.log)

**Comment by Leviathonlx** [comment]
I'm not crashing nor are others. I'd suggest trying resubbing.

**Comment by AlexWyrmin** [comment]
And now the issue isn't one anymore, thank you.
