### ISSUE TITLE
tradition_sinicized_culture localization error

### ISSUE THREAD

**Issue by JorWod** [Leviathonlx/MoreBookmarks-Plus#151]
Finding localization errors with a couple of the culture traditions. Depending on country of playthrough these can vary.  Below is an example.

Irish culture -> region traditions -> tradition_sinicized_culture_name

MB+ and all compatches are loaded at the bottom of the playset. (clean install of all mods and mods folder binned before install)

**Comment by Leviathonlx** [comment]
This stuff was fixed I just haven't updated the git for a while and am holding off on updating the mod since my current changes will destroy saves.

**Comment by JorWod** [comment]
Nice, thanks for the reply. Look forward to the update. Do you have an updated discord link? The link on the workshop seems to have expired.
