### ISSUE TITLE
Vimaranes-Surunbaqi De Jure War over Burtuqál claim_cb war not working

### ISSUE THREAD

**Issue by Benjaminlooi** [Leviathonlx/MoreBookmarks-Plus#78]
c_porto is not won after winning the war as portugal start date war 1 Jan 867

**Comment by Leviathonlx** [comment]
I'm unable to figure out why that war isn't working properly when others work just fine so I just commented it out and gave the claim for the title to the character as it works just fine that way.

**Comment by Benjaminlooi** [comment]
After giving him pressed_claim for c_porto, the start date war to claim c_porto is working fine.
Re-added start date war in #79
