### ISSUE TITLE
Paradox.com Mod Update for 1.5?

### ISSUE THREAD

**Issue by JustParadise** [Leviathonlx/MoreBookmarks-Plus#82]
Hi, I was just wondering if you could make this mod available on the paradox website in addition to the steam that you update regularly. 

I don't know if you own this mods posting, but this link has the post of your mod with the most downloads https://mods.paradoxplaza.com/mods/13438/Any

**Comment by Leviathonlx** [comment]
Hey. Paradox Plaza tends to cause...issues so I'm waiting till everything is all done on my end before doing any sort of upload there
